// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "book/curriculum/pkg/endpoint"
	pb "book/curriculum/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	curriculumList grpc.Handler
	curriculum     grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.CurriculumServer {
	return &grpcServer{
		curriculum:     makeCurriculumHandler(endpoints, options["Curriculum"]),
		curriculumList: makeCurriculumListHandler(endpoints, options["CurriculumList"]),
	}
}
