// Code generated by protoc-gen-go. DO NOT EDIT.
// source: curriculum.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CurriculumInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurriculumInfo) Reset()         { *m = CurriculumInfo{} }
func (m *CurriculumInfo) String() string { return proto.CompactTextString(m) }
func (*CurriculumInfo) ProtoMessage()    {}
func (*CurriculumInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba5ff3ac13c99eef, []int{0}
}

func (m *CurriculumInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurriculumInfo.Unmarshal(m, b)
}
func (m *CurriculumInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurriculumInfo.Marshal(b, m, deterministic)
}
func (m *CurriculumInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurriculumInfo.Merge(m, src)
}
func (m *CurriculumInfo) XXX_Size() int {
	return xxx_messageInfo_CurriculumInfo.Size(m)
}
func (m *CurriculumInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CurriculumInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CurriculumInfo proto.InternalMessageInfo

func (m *CurriculumInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CurriculumInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CurriculumInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CurriculumInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type CurriculumListRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurriculumListRequest) Reset()         { *m = CurriculumListRequest{} }
func (m *CurriculumListRequest) String() string { return proto.CompactTextString(m) }
func (*CurriculumListRequest) ProtoMessage()    {}
func (*CurriculumListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba5ff3ac13c99eef, []int{1}
}

func (m *CurriculumListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurriculumListRequest.Unmarshal(m, b)
}
func (m *CurriculumListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurriculumListRequest.Marshal(b, m, deterministic)
}
func (m *CurriculumListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurriculumListRequest.Merge(m, src)
}
func (m *CurriculumListRequest) XXX_Size() int {
	return xxx_messageInfo_CurriculumListRequest.Size(m)
}
func (m *CurriculumListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurriculumListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurriculumListRequest proto.InternalMessageInfo

func (m *CurriculumListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CurriculumListReply struct {
	Info                 []*CurriculumInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CurriculumListReply) Reset()         { *m = CurriculumListReply{} }
func (m *CurriculumListReply) String() string { return proto.CompactTextString(m) }
func (*CurriculumListReply) ProtoMessage()    {}
func (*CurriculumListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba5ff3ac13c99eef, []int{2}
}

func (m *CurriculumListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurriculumListReply.Unmarshal(m, b)
}
func (m *CurriculumListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurriculumListReply.Marshal(b, m, deterministic)
}
func (m *CurriculumListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurriculumListReply.Merge(m, src)
}
func (m *CurriculumListReply) XXX_Size() int {
	return xxx_messageInfo_CurriculumListReply.Size(m)
}
func (m *CurriculumListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CurriculumListReply.DiscardUnknown(m)
}

var xxx_messageInfo_CurriculumListReply proto.InternalMessageInfo

func (m *CurriculumListReply) GetInfo() []*CurriculumInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type CurriculumRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurriculumRequest) Reset()         { *m = CurriculumRequest{} }
func (m *CurriculumRequest) String() string { return proto.CompactTextString(m) }
func (*CurriculumRequest) ProtoMessage()    {}
func (*CurriculumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba5ff3ac13c99eef, []int{3}
}

func (m *CurriculumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurriculumRequest.Unmarshal(m, b)
}
func (m *CurriculumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurriculumRequest.Marshal(b, m, deterministic)
}
func (m *CurriculumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurriculumRequest.Merge(m, src)
}
func (m *CurriculumRequest) XXX_Size() int {
	return xxx_messageInfo_CurriculumRequest.Size(m)
}
func (m *CurriculumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CurriculumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CurriculumRequest proto.InternalMessageInfo

func (m *CurriculumRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type CurriculumReply struct {
	Info                 *CurriculumInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CurriculumReply) Reset()         { *m = CurriculumReply{} }
func (m *CurriculumReply) String() string { return proto.CompactTextString(m) }
func (*CurriculumReply) ProtoMessage()    {}
func (*CurriculumReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba5ff3ac13c99eef, []int{4}
}

func (m *CurriculumReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CurriculumReply.Unmarshal(m, b)
}
func (m *CurriculumReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CurriculumReply.Marshal(b, m, deterministic)
}
func (m *CurriculumReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurriculumReply.Merge(m, src)
}
func (m *CurriculumReply) XXX_Size() int {
	return xxx_messageInfo_CurriculumReply.Size(m)
}
func (m *CurriculumReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CurriculumReply.DiscardUnknown(m)
}

var xxx_messageInfo_CurriculumReply proto.InternalMessageInfo

func (m *CurriculumReply) GetInfo() *CurriculumInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*CurriculumInfo)(nil), "pb.CurriculumInfo")
	proto.RegisterType((*CurriculumListRequest)(nil), "pb.CurriculumListRequest")
	proto.RegisterType((*CurriculumListReply)(nil), "pb.CurriculumListReply")
	proto.RegisterType((*CurriculumRequest)(nil), "pb.CurriculumRequest")
	proto.RegisterType((*CurriculumReply)(nil), "pb.CurriculumReply")
}

func init() { proto.RegisterFile("curriculum.proto", fileDescriptor_ba5ff3ac13c99eef) }

var fileDescriptor_ba5ff3ac13c99eef = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2e, 0x2d, 0x2a,
	0xca, 0x4c, 0x2e, 0xcd, 0x29, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0x4a, 0xe2, 0xe2, 0x73, 0x86, 0x8b, 0x7b, 0xe6, 0xa5, 0xe5, 0x0b, 0xf1, 0x71, 0x31, 0x79,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x79, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0x85,
	0x16, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x81, 0xc5, 0xa0, 0x3c, 0x21, 0x11, 0x2e, 0xd6, 0x90,
	0xcc, 0x92, 0x9c, 0x54, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x88, 0x8b,
	0xc5, 0x25, 0xb5, 0x38, 0x59, 0x82, 0x05, 0x2c, 0x08, 0x66, 0x2b, 0xe9, 0x73, 0x89, 0x22, 0xec,
	0xf0, 0xc9, 0x2c, 0x2e, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x41, 0x32, 0x9a, 0x11, 0xd9,
	0x68, 0x25, 0x5b, 0x2e, 0x61, 0x74, 0x0d, 0x05, 0x39, 0x95, 0x42, 0x6a, 0x5c, 0x2c, 0x99, 0x79,
	0x69, 0xf9, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x42, 0x7a, 0x05, 0x49, 0x7a, 0xa8, 0x6e,
	0x0f, 0x02, 0xcb, 0x2b, 0x29, 0x73, 0x09, 0x22, 0xc4, 0x61, 0x76, 0x81, 0xbc, 0xe5, 0x02, 0xf7,
	0x96, 0x8b, 0x92, 0x25, 0x17, 0x3f, 0xb2, 0x22, 0x54, 0xf3, 0x19, 0xf1, 0x99, 0x6f, 0xd4, 0xc3,
	0xc8, 0xc5, 0x85, 0x90, 0x10, 0x72, 0x41, 0x0e, 0x42, 0x90, 0x6b, 0x85, 0x24, 0x51, 0xb5, 0x22,
	0x79, 0x59, 0x4a, 0x1c, 0x9b, 0x14, 0xc8, 0x72, 0x0b, 0x14, 0x33, 0x45, 0x51, 0x95, 0xc1, 0x74,
	0x0b, 0xa3, 0x0b, 0x17, 0xe4, 0x54, 0x26, 0xb1, 0x81, 0x63, 0xd3, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x2f, 0xa2, 0x96, 0x75, 0xe1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CurriculumClient is the client API for Curriculum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CurriculumClient interface {
	CurriculumList(ctx context.Context, in *CurriculumListRequest, opts ...grpc.CallOption) (*CurriculumListReply, error)
	Curriculum(ctx context.Context, in *CurriculumRequest, opts ...grpc.CallOption) (*CurriculumReply, error)
}

type curriculumClient struct {
	cc *grpc.ClientConn
}

func NewCurriculumClient(cc *grpc.ClientConn) CurriculumClient {
	return &curriculumClient{cc}
}

func (c *curriculumClient) CurriculumList(ctx context.Context, in *CurriculumListRequest, opts ...grpc.CallOption) (*CurriculumListReply, error) {
	out := new(CurriculumListReply)
	err := c.cc.Invoke(ctx, "/pb.Curriculum/CurriculumList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curriculumClient) Curriculum(ctx context.Context, in *CurriculumRequest, opts ...grpc.CallOption) (*CurriculumReply, error) {
	out := new(CurriculumReply)
	err := c.cc.Invoke(ctx, "/pb.Curriculum/Curriculum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurriculumServer is the server API for Curriculum service.
type CurriculumServer interface {
	CurriculumList(context.Context, *CurriculumListRequest) (*CurriculumListReply, error)
	Curriculum(context.Context, *CurriculumRequest) (*CurriculumReply, error)
}

func RegisterCurriculumServer(s *grpc.Server, srv CurriculumServer) {
	s.RegisterService(&_Curriculum_serviceDesc, srv)
}

func _Curriculum_CurriculumList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurriculumListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).CurriculumList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Curriculum/CurriculumList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).CurriculumList(ctx, req.(*CurriculumListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curriculum_Curriculum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurriculumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).Curriculum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Curriculum/Curriculum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).Curriculum(ctx, req.(*CurriculumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Curriculum_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Curriculum",
	HandlerType: (*CurriculumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CurriculumList",
			Handler:    _Curriculum_CurriculumList_Handler,
		},
		{
			MethodName: "Curriculum",
			Handler:    _Curriculum_Curriculum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "curriculum.proto",
}
