// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "book/userapi/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeRegisterHandler(m, endpoints, options["Register"])
	makeLoginHandler(m, endpoints, options["Login"])
	makeGetUserInfoHandler(m, endpoints, options["GetUserInfo"])
	makeTestHandler(m, endpoints, options["Test"])
	makeTestApiHandler(m, endpoints, options["TestApi"])
	return m
}
