// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailMessageRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailMessageRequest) Reset()         { *m = SendEmailMessageRequest{} }
func (m *SendEmailMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailMessageRequest) ProtoMessage()    {}
func (*SendEmailMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SendEmailMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailMessageRequest.Unmarshal(m, b)
}
func (m *SendEmailMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailMessageRequest.Merge(m, src)
}
func (m *SendEmailMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailMessageRequest.Size(m)
}
func (m *SendEmailMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailMessageRequest proto.InternalMessageInfo

func (m *SendEmailMessageRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *SendEmailMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendEmailMessageReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailMessageReply) Reset()         { *m = SendEmailMessageReply{} }
func (m *SendEmailMessageReply) String() string { return proto.CompactTextString(m) }
func (*SendEmailMessageReply) ProtoMessage()    {}
func (*SendEmailMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *SendEmailMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailMessageReply.Unmarshal(m, b)
}
func (m *SendEmailMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailMessageReply.Marshal(b, m, deterministic)
}
func (m *SendEmailMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailMessageReply.Merge(m, src)
}
func (m *SendEmailMessageReply) XXX_Size() int {
	return xxx_messageInfo_SendEmailMessageReply.Size(m)
}
func (m *SendEmailMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailMessageReply proto.InternalMessageInfo

type SendPhoneMessageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPhoneMessageRequest) Reset()         { *m = SendPhoneMessageRequest{} }
func (m *SendPhoneMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendPhoneMessageRequest) ProtoMessage()    {}
func (*SendPhoneMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *SendPhoneMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPhoneMessageRequest.Unmarshal(m, b)
}
func (m *SendPhoneMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPhoneMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendPhoneMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPhoneMessageRequest.Merge(m, src)
}
func (m *SendPhoneMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendPhoneMessageRequest.Size(m)
}
func (m *SendPhoneMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPhoneMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPhoneMessageRequest proto.InternalMessageInfo

type SendPhoneMessageReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPhoneMessageReply) Reset()         { *m = SendPhoneMessageReply{} }
func (m *SendPhoneMessageReply) String() string { return proto.CompactTextString(m) }
func (*SendPhoneMessageReply) ProtoMessage()    {}
func (*SendPhoneMessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SendPhoneMessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPhoneMessageReply.Unmarshal(m, b)
}
func (m *SendPhoneMessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPhoneMessageReply.Marshal(b, m, deterministic)
}
func (m *SendPhoneMessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPhoneMessageReply.Merge(m, src)
}
func (m *SendPhoneMessageReply) XXX_Size() int {
	return xxx_messageInfo_SendPhoneMessageReply.Size(m)
}
func (m *SendPhoneMessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPhoneMessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendPhoneMessageReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendEmailMessageRequest)(nil), "pb.SendEmailMessageRequest")
	proto.RegisterType((*SendEmailMessageReply)(nil), "pb.SendEmailMessageReply")
	proto.RegisterType((*SendPhoneMessageRequest)(nil), "pb.SendPhoneMessageRequest")
	proto.RegisterType((*SendPhoneMessageReply)(nil), "pb.SendPhoneMessageReply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe5,
	0x12, 0x0f, 0x4e, 0xcd, 0x4b, 0x71, 0xcd, 0x4d, 0xcc, 0xcc, 0xf1, 0x85, 0xc8, 0x06, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0x82, 0x84, 0x25, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x92, 0xd4, 0x8a, 0x12, 0x09, 0x26, 0xb0, 0x20,
	0x98, 0x2d, 0x24, 0xc1, 0xc5, 0x9e, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x57, 0x22, 0xc1, 0x0c, 0x16,
	0x86, 0x71, 0x95, 0xc4, 0xb9, 0x44, 0x31, 0x8d, 0x2f, 0xc8, 0xa9, 0x54, 0x92, 0x84, 0xd8, 0x1b,
	0x90, 0x91, 0x9f, 0x97, 0x8a, 0x6a, 0x2f, 0x4c, 0x0f, 0xaa, 0x54, 0x41, 0x4e, 0xa5, 0xd1, 0x42,
	0x46, 0x2e, 0x76, 0xa8, 0x80, 0x90, 0x17, 0x97, 0x00, 0xba, 0xc1, 0x42, 0xd2, 0x7a, 0x05, 0x49,
	0x7a, 0x38, 0x7c, 0x23, 0x25, 0x89, 0x5d, 0xb2, 0x20, 0xa7, 0x12, 0x66, 0x16, 0xb2, 0x85, 0x08,
	0xb3, 0xb0, 0xb8, 0x10, 0x61, 0x16, 0x86, 0x1b, 0x93, 0xd8, 0xc0, 0x41, 0x6b, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0x85, 0xab, 0xba, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	SendEmailMessage(ctx context.Context, in *SendEmailMessageRequest, opts ...grpc.CallOption) (*SendEmailMessageReply, error)
	SendPhoneMessage(ctx context.Context, in *SendPhoneMessageRequest, opts ...grpc.CallOption) (*SendPhoneMessageReply, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendEmailMessage(ctx context.Context, in *SendEmailMessageRequest, opts ...grpc.CallOption) (*SendEmailMessageReply, error) {
	out := new(SendEmailMessageReply)
	err := c.cc.Invoke(ctx, "/pb.Message/SendEmailMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendPhoneMessage(ctx context.Context, in *SendPhoneMessageRequest, opts ...grpc.CallOption) (*SendPhoneMessageReply, error) {
	out := new(SendPhoneMessageReply)
	err := c.cc.Invoke(ctx, "/pb.Message/SendPhoneMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	SendEmailMessage(context.Context, *SendEmailMessageRequest) (*SendEmailMessageReply, error)
	SendPhoneMessage(context.Context, *SendPhoneMessageRequest) (*SendPhoneMessageReply, error)
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_SendEmailMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendEmailMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/SendEmailMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendEmailMessage(ctx, req.(*SendEmailMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendPhoneMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPhoneMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendPhoneMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/SendPhoneMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendPhoneMessage(ctx, req.(*SendPhoneMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmailMessage",
			Handler:    _Message_SendEmailMessage_Handler,
		},
		{
			MethodName: "SendPhoneMessage",
			Handler:    _Message_SendPhoneMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
