// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "book/message/pkg/endpoint"
	pb "book/message/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sendEmailMessage grpc.Handler
	sendPhoneMessage grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.MessageServer {
	return &grpcServer{
		sendEmailMessage: makeSendEmailMessageHandler(endpoints, options["SendEmailMessage"]),
		sendPhoneMessage: makeSendPhoneMessageHandler(endpoints, options["SendPhoneMessage"]),
	}
}
