// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mobile               int64    `protobuf:"varint,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Age                  int64    `protobuf:"varint,5,opt,name=Age,proto3" json:"Age,omitempty"`
	CreateTime           string   `protobuf:"bytes,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetMobile() int64 {
	if m != nil {
		return m.Mobile
	}
	return 0
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type RegisterRequest struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserInfoByIdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoByIdRequest) Reset()         { *m = UserInfoByIdRequest{} }
func (m *UserInfoByIdRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoByIdRequest) ProtoMessage()    {}
func (*UserInfoByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfoByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoByIdRequest.Unmarshal(m, b)
}
func (m *UserInfoByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoByIdRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoByIdRequest.Merge(m, src)
}
func (m *UserInfoByIdRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoByIdRequest.Size(m)
}
func (m *UserInfoByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoByIdRequest proto.InternalMessageInfo

func (m *UserInfoByIdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserInfoByIdReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoByIdReply) Reset()         { *m = UserInfoByIdReply{} }
func (m *UserInfoByIdReply) String() string { return proto.CompactTextString(m) }
func (*UserInfoByIdReply) ProtoMessage()    {}
func (*UserInfoByIdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserInfoByIdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoByIdReply.Unmarshal(m, b)
}
func (m *UserInfoByIdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoByIdReply.Marshal(b, m, deterministic)
}
func (m *UserInfoByIdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoByIdReply.Merge(m, src)
}
func (m *UserInfoByIdReply) XXX_Size() int {
	return xxx_messageInfo_UserInfoByIdReply.Size(m)
}
func (m *UserInfoByIdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoByIdReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoByIdReply proto.InternalMessageInfo

func (m *UserInfoByIdReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserInfoByPhoneRequest struct {
	Phone                int64    `protobuf:"varint,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoByPhoneRequest) Reset()         { *m = UserInfoByPhoneRequest{} }
func (m *UserInfoByPhoneRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoByPhoneRequest) ProtoMessage()    {}
func (*UserInfoByPhoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfoByPhoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoByPhoneRequest.Unmarshal(m, b)
}
func (m *UserInfoByPhoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoByPhoneRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoByPhoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoByPhoneRequest.Merge(m, src)
}
func (m *UserInfoByPhoneRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoByPhoneRequest.Size(m)
}
func (m *UserInfoByPhoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoByPhoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoByPhoneRequest proto.InternalMessageInfo

func (m *UserInfoByPhoneRequest) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

type UserInfoByPhoneReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoByPhoneReply) Reset()         { *m = UserInfoByPhoneReply{} }
func (m *UserInfoByPhoneReply) String() string { return proto.CompactTextString(m) }
func (*UserInfoByPhoneReply) ProtoMessage()    {}
func (*UserInfoByPhoneReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserInfoByPhoneReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoByPhoneReply.Unmarshal(m, b)
}
func (m *UserInfoByPhoneReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoByPhoneReply.Marshal(b, m, deterministic)
}
func (m *UserInfoByPhoneReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoByPhoneReply.Merge(m, src)
}
func (m *UserInfoByPhoneReply) XXX_Size() int {
	return xxx_messageInfo_UserInfoByPhoneReply.Size(m)
}
func (m *UserInfoByPhoneReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoByPhoneReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoByPhoneReply proto.InternalMessageInfo

func (m *UserInfoByPhoneReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "pb.UserInfo")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "pb.RegisterReply")
	proto.RegisterType((*UserInfoByIdRequest)(nil), "pb.UserInfoByIdRequest")
	proto.RegisterType((*UserInfoByIdReply)(nil), "pb.UserInfoByIdReply")
	proto.RegisterType((*UserInfoByPhoneRequest)(nil), "pb.UserInfoByPhoneRequest")
	proto.RegisterType((*UserInfoByPhoneReply)(nil), "pb.UserInfoByPhoneReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0xe9, 0x07, 0x75, 0xac, 0xad, 0x9d, 0xd6, 0xba, 0xe4, 0x20, 0x25, 0x20, 0xf4, 0x14,
	0xb0, 0x45, 0xf0, 0x24, 0xa8, 0x88, 0xe4, 0x20, 0x94, 0xa0, 0x3f, 0xa0, 0x21, 0x63, 0x5d, 0x48,
	0xbb, 0xeb, 0x6e, 0x8a, 0xf4, 0x8f, 0xf8, 0x87, 0xfc, 0x63, 0xb2, 0xdb, 0xa6, 0x4d, 0x5b, 0x0f,
	0xb9, 0xe5, 0xbd, 0x79, 0x33, 0xef, 0xed, 0x23, 0x00, 0x4b, 0x4d, 0x2a, 0x90, 0x4a, 0x64, 0x02,
	0x5d, 0x19, 0xfb, 0x3f, 0x0e, 0x34, 0xde, 0x35, 0xa9, 0x70, 0xf1, 0x21, 0xb0, 0x05, 0x6e, 0x98,
	0x30, 0x67, 0xe0, 0x0c, 0x2b, 0x91, 0x1b, 0x26, 0xd8, 0x87, 0xfa, 0xab, 0x88, 0x79, 0x4a, 0xcc,
	0xb5, 0xdc, 0x06, 0x61, 0x0f, 0x6a, 0xcf, 0xf3, 0x29, 0x4f, 0x59, 0x65, 0xe0, 0x0c, 0x4f, 0xa2,
	0x35, 0x40, 0x0f, 0x1a, 0x93, 0xa9, 0xd6, 0xdf, 0x42, 0x25, 0xac, 0x6a, 0x07, 0x5b, 0x8c, 0xe7,
	0x50, 0x79, 0x98, 0x11, 0xab, 0xd9, 0x33, 0xe6, 0x13, 0xaf, 0x00, 0x9e, 0x14, 0x4d, 0x33, 0x7a,
	0xe3, 0x73, 0x62, 0x75, 0xab, 0x2f, 0x30, 0xfe, 0x18, 0xda, 0x11, 0xcd, 0xb8, 0xce, 0x48, 0x45,
	0xf4, 0xb5, 0x24, 0x9d, 0xe1, 0x00, 0xaa, 0x26, 0xbd, 0x0d, 0x78, 0x3a, 0x6a, 0x06, 0x32, 0x0e,
	0xf2, 0xe8, 0x91, 0x9d, 0xf8, 0x37, 0x70, 0xb6, 0x5b, 0x92, 0xe9, 0xaa, 0xc4, 0xca, 0x35, 0x74,
	0x73, 0xe6, 0x71, 0x15, 0x26, 0xb9, 0x57, 0x0b, 0x5c, 0xbe, 0xad, 0x82, 0x27, 0xfe, 0x2d, 0x74,
	0xf6, 0x65, 0xe5, 0xae, 0x07, 0xd0, 0xdf, 0xad, 0x4d, 0x3e, 0xc5, 0x82, 0x72, 0x83, 0x1e, 0xd4,
	0xa4, 0xc1, 0x1b, 0x8f, 0x35, 0xf0, 0xef, 0xa0, 0x77, 0xa4, 0x2f, 0xe5, 0x34, 0xfa, 0x75, 0xa0,
	0x6a, 0x28, 0x1c, 0x41, 0x23, 0xef, 0x00, 0xbb, 0x46, 0x78, 0x50, 0xa3, 0xd7, 0xd9, 0x27, 0xcd,
	0xf9, 0x7b, 0x68, 0x16, 0x5f, 0x87, 0x97, 0x45, 0x83, 0x42, 0x2d, 0xde, 0xc5, 0xf1, 0xc0, 0xec,
	0xbf, 0x40, 0xfb, 0x20, 0x36, 0x7a, 0xfb, 0xca, 0xe2, 0xdb, 0x3d, 0xf6, 0xef, 0x4c, 0xa6, 0xab,
	0xb8, 0x6e, 0xff, 0xcc, 0xf1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x3d, 0x9d, 0x2c, 0xa7,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	UserInfoById(ctx context.Context, in *UserInfoByIdRequest, opts ...grpc.CallOption) (*UserInfoByIdReply, error)
	UserInfoByPhone(ctx context.Context, in *UserInfoByPhoneRequest, opts ...grpc.CallOption) (*UserInfoByPhoneReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/pb.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfoById(ctx context.Context, in *UserInfoByIdRequest, opts ...grpc.CallOption) (*UserInfoByIdReply, error) {
	out := new(UserInfoByIdReply)
	err := c.cc.Invoke(ctx, "/pb.User/UserInfoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserInfoByPhone(ctx context.Context, in *UserInfoByPhoneRequest, opts ...grpc.CallOption) (*UserInfoByPhoneReply, error) {
	out := new(UserInfoByPhoneReply)
	err := c.cc.Invoke(ctx, "/pb.User/UserInfoByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	UserInfoById(context.Context, *UserInfoByIdRequest) (*UserInfoByIdReply, error)
	UserInfoByPhone(context.Context, *UserInfoByPhoneRequest) (*UserInfoByPhoneReply, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserInfoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserInfoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.User/UserInfoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserInfoById(ctx, req.(*UserInfoByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserInfoByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoByPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserInfoByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.User/UserInfoByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserInfoByPhone(ctx, req.(*UserInfoByPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "UserInfoById",
			Handler:    _User_UserInfoById_Handler,
		},
		{
			MethodName: "UserInfoByPhone",
			Handler:    _User_UserInfoByPhone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
