// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "book/message/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	SendEmailMessageEndpoint endpoint.Endpoint
	SendPhoneMessageEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.MessageService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		SendEmailMessageEndpoint: MakeSendEmailMessageEndpoint(s),
		SendPhoneMessageEndpoint: MakeSendPhoneMessageEndpoint(s),
	}
	for _, m := range mdw["SendEmailMessage"] {
		eps.SendEmailMessageEndpoint = m(eps.SendEmailMessageEndpoint)
	}
	for _, m := range mdw["SendPhoneMessage"] {
		eps.SendPhoneMessageEndpoint = m(eps.SendPhoneMessageEndpoint)
	}
	return eps
}
